# Generated by Django 5.2.8 on 2025-11-28 22:35

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('nombre_proveedor', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre del proveedor solo puede contener letras, números, espacios, puntos y guiones.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\.\\-]+$')], verbose_name='Nombre del Proveedor')),
                ('rut_proveedor', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-9 (o 1234567-9)', regex='^[0-9]{7,8}-[0-9kK]{1}$')], verbose_name='RUT Proveedor')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite de Pago')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cuenta por Pagar',
                'verbose_name_plural': 'Cuentas por Pagar',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Pagado')),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('otros', 'Otros')], default='transferencia', max_length=20, verbose_name='Método de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('anulado', 'Anulado')], max_length=20, verbose_name='Estado del Pago')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='presupuestos.cuentaporpagar', verbose_name='Cuenta por Pagar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Pago',
                'verbose_name_plural': 'Historial de Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Presupuesto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10, verbose_name='Estado')),
                ('periodo', models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensual', max_length=20, verbose_name='Período')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Ítem')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('monto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Monto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuestos.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Ítem de Presupuesto',
                'verbose_name_plural': 'Ítems de Presupuesto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Pagado')),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otros', 'Otros')], default='transferencia', max_length=20, verbose_name='Método de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('item_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='presupuestos.itempresupuesto', verbose_name='Ítem del Presupuesto')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='presupuestos.presupuesto', verbose_name='Presupuesto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddConstraint(
            model_name='itempresupuesto',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('presupuesto'), name='unique_item_nombre_por_presupuesto_ci'),
        ),
    ]
